feat: Added blog for EMG Armband.
SRA-VJTI/blog pull request #50
Opened 2024-07-27 11:39 UTC by vovw

[x] formatting
[x] grammar check

2024-07-29 08:33 UTC, SuperChamp234 requested changes

2024-07-29 08:33 UTC, SuperChamp234 commented on _posts/2020-09-14-using-jekyll-with-github-pages-1.md
What was changed in this file?

2024-07-29 08:33 UTC, SuperChamp234 commented on assets/posts/.DS_Store
Get rid of this file please

2024-07-29 08:33 UTC, SuperChamp234 commented on assets/posts/emg-armband/.DS_Store
Get rid of this file please

2024-07-29 08:34 UTC, SuperChamp234 commented
Maintainers, please make sure to squash and merge when this is ready.

2024-07-29 08:34 UTC, SuperChamp234 commented
> * grammer and formatting done.
> 
>     * added the images
> 
>     * added the sponsor logo
> 
>     * added the sponsor links
> 
>     * added information about whats next
> 
>     * added link to the github repo

Please do try to add a better description, even if short.

2024-07-29 08:40 UTC, RapidRoger18 commented
Add the updates on weekly/biweekly basis, so 4 weeks of updates.

2024-07-29 09:09 UTC, vovw commented
@RapidRoger18 @SuperChamp234 updated the description for the pr and added the weekly updates. Looks good?

2024-07-29 10:23 UTC, SuperChamp234 commented
> @RapidRoger18 @SuperChamp234 updated the description for the pr and added the weekly updates. Looks good?

Yeah, looks good! I won't review the blog contents, that's all up to you....

2024-07-29 10:24 UTC, SuperChamp234 commented on _posts/2020-09-14-using-jekyll-with-github-pages-1.md
Why was this resolved?

2024-07-29 18:21 UTC, vovw commented on _posts/2020-09-14-using-jekyll-with-github-pages-1.md
accidentally added a new line

2024-07-30 08:42 UTC, vovw commented on _posts/2020-09-14-using-jekyll-with-github-pages-1.md
done

2024-07-30 08:42 UTC, merged